name: Generate Lua library
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'rts/Lua/**'
jobs:
  generate-library:
    name: Regenerate library
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Lua CPP files
        uses: actions/checkout@v4
        with:
          sparse-checkout: rts/Lua
          path: recoil

      # Add file patterns for any files that contain Lua docs to be parsed by
      # lua-doc-extractor. Patterns should be space separated.
      - name: Define paths
        id: paths
        run: |
          paths='rts/Lua/*.cpp'
          echo "lua_paths=$paths" >> $env:GITHUB_OUTPUT

      # Get sha of latest commit that updated files in the FmodProject folder
      - name: Get version of Lua definitions
        id: lua-version
        working-directory: recoil
        env:
          LUA_PATHS: ${{ steps.paths.outputs.lua_paths }}
        run: |
          commit=$(git log -n 1 --format=format:%H $LUA_PATHS)
          echo "version=$commit" >> $env:GITHUB_OUTPUT

      - name: Check out library repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.RECOIL_LUA_LIBRARY_RESPOSITORY }}
          ssh-key: ${{ secrets.RECOIL_LUA_LIBRARY_SSH_KEY }}
          path: library

      - name: Check library version
        id: library-version
        working-directory: library
        run: |
          version=$(cat .recoil-version || true)
          echo "version=$version" >> $env:GITHUB_OUTPUT

      # NOTE: This step is duplicated in `publish-site.yml`
      - name: Generate Lua library
        working-directory: recoil
        if: steps.lua-version.outputs.version != steps.library-version.outputs.version
        env:
          LUA_PATHS: ${{ steps.paths.outputs.lua_paths }}
        run: |
          npm install -g lua-doc-extractor@3
          lua-doc-extractor $LUA_PATHS \
            --dest rts/Lua/library/generated \
            --repo https://github.com/${{ github.repository }}/blob/${{ github.sha }}

      - name: Copy changes into library repo
        if: steps.lua-version.outputs.version != steps.library-version.outputs.version
        env:
          VERSION: ${{ steps.lua-version.outputs.version }}
        run: |
          # Copy library
          rm -rf library/library
          cp -r recoil/rts/Lua/library library

          # Update version
          echo $VERSION > library/.recoil-version

      # Always try to update library repo (even if generation did not make changes).
      # Hand-written files may have changed without generated output changing,
      # and library may simply be out of date for whatever reason.
      - name: Commit and push library repo
        if: steps.lua-version.outputs.version != steps.library-version.outputs.version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./library
          commit_message: |
            Update library
            Generated from https://github.com/${{ github.repository }}/commit/${{ github.sha }}